Calendar component
hack4impact-uiuc/glen-world pull request #12
Opened 2020-02-28 05:39 UTC by AngelaLuo49021

2020-02-28 16:12 UTC, chyku commented
Could you add screen shots + make sure to run formatting?

2020-03-03 19:13 UTC, chyku requested changes
:fire: great :fire: work :fire:

2020-03-03 19:13 UTC, chyku commented on src/components/AssignmentPage/AssignmentPage.js
> +      }}
why is this inline styled?

2020-03-03 19:13 UTC, chyku commented on src/components/CalendarComponent/CalendarComponent.js
> +function CalendarComponent(props) {
hmm could you rename this to Calendar or DateSelector, just following along with Jason's naming standards

2020-03-03 19:13 UTC, chyku commented on src/components/AssignmentPage/AssignmentPage.js
> +function AssignmentPage() {
SICK FUNCTIONAL REACT COMPONENT U GOT THERE

2020-03-03 19:13 UTC, chyku commented on src/components/ExampleComponent/ExampleComponent.js
> +        })
once the other pr gets merged in this probably wont be a thing or itll cause conflicts just a note

2020-03-03 23:18 UTC, rxun approved these changes

2020-03-04 00:48 UTC, chyku approved these changes
:fire:

2020-03-04 00:48 UTC, merged