Restyle word selection
hack4impact-uiuc/glen-world pull request #61
Opened 2020-04-09 18:38 UTC by AngelaLuo49021

## Status:

## Description :star2:

Making the word selection part look purty
Fixes #number
 
## TODOs :star:

2020-04-17 15:26 UTC, chyku requested changes
naming hurts me

2020-04-17 15:26 UTC, chyku commented on src/components/PhonicWordSelector/PhonicWordSelector.js
> +    }
you can make this into one line by using `selected` as the first param

2020-04-17 15:26 UTC, chyku commented on src/components/PhonicWordSelector/PhonicWordSelector.js
> +  function wordDisplay(word) {
Can you capitalize this -> `WordDisplay` bc it's acting like a sort of component

2020-04-17 15:26 UTC, chyku commented on src/components/WordGroupIcon/WordGroupIcon.js
> +      <img src={props.image} className="image" />
is the `image` class just for these icons? in that case it should have a slightly more specific name

2020-04-17 15:26 UTC, chyku commented on src/components/WordGroupIcon/WordGroupIcon.scss
> +  // color: $assignments-font-color;
pls delete this comment

2020-04-17 15:26 UTC, chyku commented on src/components/WordGroupIcon/WordGroupIcon.scss
> +  color: violet;
woooah what color is this LOL

2020-04-17 15:26 UTC, chyku commented on src/components/WordGroupSelector/WordGroupSelector.js
>          setWordGroups({
pls add documentation for what each index in these arrays represent- or you could make them objects with descriptive keys ie 
``` javascript
    People: {
            words: collectedWordGroups[wordKeys.current[0]],
            image: "images/word-group/person.svg",
            index: 0
          },
```
or sth like that

2020-04-17 15:26 UTC, chyku commented on src/components/WordSelector/WordSelector.js
> +  const [cantSelect, setCantSelect] = useState(false);
maybe rename this disableSelection or something the lack of apostrophe in "cant" is making me uncomfortable

2020-04-17 15:26 UTC, chyku commented on src/components/WordSelector/WordSelector.js
> +      }
maybe you could use the `(props.assignedWordGroup != props.name)` as the boolean instead of the if statement but that might make it more inefficient so whatever works for you

2020-04-17 15:26 UTC, chyku commented on src/components/WordSelector/WordSelector.js
> +              checked={checkedWords.includes(word) ? true : null}
does this field have to be only `true` or `null`? bc otherwise you could just do `checked={checkedWords.includes(word)}`

2020-04-17 15:26 UTC, chyku commented on src/components/WordSelector/WordSelector.js
> +        <div className="Words" key={index}>
why is the `Words` class capitalized and `word` not

2020-04-17 15:26 UTC, chyku commented on src/components/WordSelector/WordSelector.js
> +                }
same question here about whether you can use ` checkedWords.length == props.group.length && !cantSelect ` as the boolean or it has to be just true or null

2020-04-17 15:26 UTC, chyku commented on src/components/WordSelector/WordSelector.js
> +                onChange={() => handleChooseAll()}
`onChange={handleChooseAll}`

2020-04-17 15:26 UTC, chyku commented on src/components/WordSelector/WordSelector.scss
>  .WordSelector {
i'm not sure what you've been using up til now but camelcase might be preferable

2020-04-17 15:26 UTC, chyku commented on src/components/PhonicIcon/PhonicIcon.scss
> +color: $assignments-font-color;
:(

2020-04-17 15:26 UTC, chyku commented on src/components/WordGroupSelector/squiggly.svg
> +<svg width="1500" height="1500" viewBox="0 0 1319 1062" fill="none" xmlns="http://www.w3.org/2000/svg">
if this is the squiggly for the background maybe name it wordgroupbg or something instead of squiggly LOL

2020-04-21 21:01 UTC, AngelaLuo49021 commented on src/components/WordSelector/WordSelector.scss
>  .WordSelector {
lol all the code ive been working w/ hasn't been camelcase so idk who started that trend

2020-04-21 21:02 UTC, AngelaLuo49021 commented on src/components/WordSelector/WordSelector.scss
>  .WordSelector {
did we want to change all of them, bc thats like all of them, nobody been camel casing :(

2020-04-22 00:57 UTC, AngelaLuo49021 commented
merge me daddyyyyyyy

2020-04-24 00:28 UTC, chyku requested changes
sum last changes

2020-04-24 00:28 UTC, chyku commented on src/components/WordSelector/WordSelector.js
> +            onClick={() => handleSelect()}
`onClick = handleSelect` PLs

2020-04-24 00:28 UTC, chyku commented on src/components/WordSelector/WordSelector.js
> +            disabled={disableNext()}
is this supposed to be `{disableNext}` or `{disableNext()}` (w the quotes) bc i know when you have the quotes it runs over and over again

2020-04-24 03:27 UTC, chyku approved these changes
approved daddy

2020-04-24 03:28 UTC, merged