custom lessons created by admin endpoint
hack4impact-uiuc/glen-world pull request #7
Opened 2020-02-21 02:43 UTC by AngelaLuo49021

2020-02-28 01:50 UTC, chyku requested changes
tiny logistical things mb

2020-02-28 01:50 UTC, chyku commented on src/components/ExampleComponent/ExampleComponent.js
>  const ExampleComponent = ({ firebase }) => {
make sure to comment this so we know it's an example LOL mb for not telling you to earlier

2020-02-28 01:50 UTC, chyku commented on src/utils/Firebase/firebase.js
> +      .where("adminAccountId", "==", adminAccountId);
can u put this underneath w/ the example endpoint

2020-03-02 01:24 UTC, chyku approved these changes
SICK

2020-03-03 23:26 UTC, rxun approved these changes

2020-03-03 23:29 UTC, chyku approved these changes

2020-03-03 23:30 UTC, merged